"""
Alembic environment.

Builds the database URL from the app's existing Settings (app/core/config.py)
instead of duplicating connection details in alembic.ini. Uses the
mysql+mysqlconnector dialect so Alembic reuses mysql-connector-python
(already a dependency for the app's runtime pool) rather than pulling in a
second MySQL driver just for migrations.
"""
from logging.config import fileConfig

from alembic import context
from sqlalchemy import engine_from_config, pool

from app.core.config import get_settings

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

settings = get_settings()
db_url = (
    f"mysql+mysqlconnector://{settings.mysql_user}:{settings.mysql_password}"
    f"@{settings.mysql_host}:{settings.mysql_port}/{settings.mysql_db}"
)
config.set_main_option("sqlalchemy.url", db_url)

target_metadata = None  # migrations are hand-written SQL (op.execute), not autogenerated from ORM models


def run_migrations_offline() -> None:
    context.configure(
        url=db_url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    with connectable.connect() as connection:
        context.configure(connection=connection, target_metadata=target_metadata)
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
